# Generated by Django 5.1.5 on 2025-08-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('action_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('foster', 'Become a Foster'), ('donate', 'Make a Donation'), ('both', 'Volunteer & Donate')], max_length=20)),
                ('interest_area', models.CharField(choices=[('rescue', 'Animal Rescue'), ('vaccination', 'Vaccination Campaign'), ('awareness', 'Education & Awareness'), ('events', 'Adoption Events'), ('fundraising', 'Fundraising'), ('other', 'Other')], max_length=50)),
                ('donation_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('subscribe_newsletter', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('admin_reply', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
