# Generated by Django 5.1.5 on 2025-08-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0002_rescuereport_delete_rescuerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuereport',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rescuereport',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
